<?php

namespace YouthConventionBundle\Repository;

/**
 * DelegatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelegatesRepository extends \Doctrine\ORM\EntityRepository
{
}
