<?php

namespace YouthConventionBundle\Repository;

/**
 * DelegatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelegatesRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findEastAction(){
//        $em = $this->getEntityManager();
//        $value = $em->createQuery("SELECT COUNT(a) FROM YouthConventionBundle:Delegates a where a.district='East'");
//        $count = $value->getSingleScalarResult();
//        return $count;
//    }
//
//    public function findNorthAction(){
//        $em = $this->getEntityManager();
//        $value = $em->createQuery("SELECT COUNT(a) FROM YouthConventionBundle:Delegates a where a.district='North'");
//        $count = $value->getSingleScalarResult();
//        return $count;
//    }
}
