<?php

namespace AppBundle\Repository;

/**
 * LastUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastUpdateRepository extends \Doctrine\ORM\EntityRepository
{
}
