app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_member:
    resource: "@AppBundle/Resources/config/routing/register.yml"
    prefix:   /member

app_task:
    resource: "@AppBundle/Resources/config/routing/task.yml"
    prefix:   /task