app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

app_member:
    resource: "@AppBundle/Resources/config/routing/register.yml"
    prefix:   /member

app_task:
    resource: "@AppBundle/Resources/config/routing/task.yml"
    prefix:   /task