app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_member:
    resource: "@AppBundle/Resources/config/routing/register.yml"
    prefix:   /member

app_task:
    resource: "@AppBundle/Resources/config/routing/task.yml"
    prefix:   /task

admin_panel:
    resource: "@DesmeeAdminBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile